blank_issues_enabled: false
contact_links:
  - name: Support Page
    url: https://puritysb.github.io/SlideTouch-support/support.html
    about: Check our FAQ and support page before filing an issue.
